name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for Workload Identity Federation

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2 # Use the dedicated auth action
      with:
        # Pass your service account key to the auth action
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        # Use Workload Identity Federation for authentication (recommended)
        # Create a Service Account, enable Workload Identity Federation,
        # and configure the GitHub OIDC provider for your project.
        # https://github.com/google-github-actions/auth#authenticating-with-workload-identity-federation
        # Replace `your-service-account-email` with your actual service account email.
        # service_account: artifact-registry-access@vlba-fraud-detection.iam.gserviceaccount.com
        # service_account_key: ${{ secrets.GCP_SA_KEY }} # Fallback for non-WIF, or if you prefer SA key
      
    - name: Debug GCloud Authentication State # <--- NEW STEP FOR DEBUGGING
      run: |
        echo "=== Authentication Debug ==="
        echo "Checking gcloud auth status..."
        gcloud auth list
        echo "Current project:"
        gcloud config get-value project
        echo "Current account:"
        gcloud config get-value account
        echo "Testing project access..."
        gcloud projects describe ${{ secrets.GCP_PROJECT_ID }} || echo "Failed to describe project"
        echo "Testing Cloud Build API access..."
        gcloud builds list --limit=1 || echo "Failed to list builds"
        echo "=== End Debug ==="
      continue-on-error: true

    - name: Set project explicitly # Add this step
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        echo "Project set to: $(gcloud config get-value project)"

    - name: Authorize Docker for GCR
      run: gcloud auth configure-docker

    - name: Get latest git tag (or use sha if no tag)
      id: get_tag
      run: |
        TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo ${{ github.sha }})
        echo "GIT_TAG=$TAG" >> $GITHUB_ENV