name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for Workload Identity Federation

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        # Use Workload Identity Federation for authentication (recommended)
        # Create a Service Account, enable Workload Identity Federation,
        # and configure the GitHub OIDC provider for your project.
        # https://github.com/google-github-actions/auth#authenticating-with-workload-identity-federation
        # Replace `your-service-account-email` with your actual service account email.
        service_account: artifact-registry-access@vlba-fraud-detection.iam.gserviceaccount.com
        service_account_key: ${{ secrets.GCP_SA_KEY }} # Fallback for non-WIF, or if you prefer SA key

    - name: Authorize Docker for GCR
      run: gcloud auth configure-docker

    - name: Get latest git tag (or use sha if no tag)
      id: get_tag
      run: |
        TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo ${{ github.sha }})
        echo "GIT_TAG=$TAG" >> $GITHUB_ENV

    - name: Trigger Cloud Build
      run: |
        gcloud builds submit --config cloudbuild.yml . \
          --substitutions=CLOUD_RUN_REGION=${{ secrets.CLOUD_RUN_REGION }},GCS_DATA_BUCKET=${{ secrets.GCS_DATA_BUCKET }},GCS_MODEL_BUCKET=${{ secrets.GCS_MODEL_BUCKET }},GIT_TAG=${{ env.GIT_TAG }}
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }} # Pass project ID as env var to gcloud command if needed